name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore JadeEncryption

    - name: Build
      run: dotnet build --configuration Release --no-restore JadeEncryption

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal JadeEncryption

    - name: Publish to GitHub Packages
      run: dotnet pack --configuration Release -o ./nupkg JadeEncryption
    - name: Publish to GitHub Packages
      run: dotnet nuget push ./nupkg/*.nupkg -s https://nuget.pkg.github.com/KaustavCodes/index.json -k ${{ secrets.MY_GITHUB_TOKEN }}
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Publish to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
